### ISSUE TITLE
AltRank - KeyError 'vt'

### ISSUE THREAD

**Issue by Gh61** [cyberjunky/3commas-cyber-bots#120]
**Describe the bug**
When running `altranky.py` script, suddenly today (2022-04-26) from about midnight UTC, `altrank.py` script started to fail on key 'vt'.

**To Reproduce**
Run `python3 altrank.py`.

**Expected behavior**
Running without exception.

**Log**
```
2022-04-26 09:49:42 - altrank - INFO - 3C Cyber Bot-Helper altrank
2022-04-26 09:49:42 - altrank - INFO - Started on Tuesday 09:49:42 2022-04-26
2022-04-26 09:49:42 - altrank - INFO - Notifications are enabled
2022-04-26 09:49:42 - altrank - INFO - Loaded configuration from '/3commas-cyber-bots/altrank.ini'
2022-04-26 09:49:42 - altrank - INFO - Reloaded configuration from '/3commas-cyber-bots/altrank.ini'
2022-04-26 09:49:42 - altrank - INFO - Fetched 3Commas pairs blacklist OK (6 pairs)
2022-04-26 09:49:42 - altrank - INFO - Fetched 3Commas BTC price OK (40642.19 USDT)
Traceback (most recent call last):
  File "/3commas-cyber-bots/altrank.py", line 359, in <module>
    lunarcrush = get_lunarcrush_data(logger, program, config, usdtbtcprice)
  File "/3commas-cyber-bots/helpers/misc.py", line 92, in get_lunarcrush_data
    f"rank:{crush['rank']:3d}  acr:{crush['acr']:4d}   gs:{crush['gs']:3.1f}   vt:{crush['vt']:8f}   "
KeyError: 'vt'
```

**Environment:**
 - Python version: 3.9.7
 - Operating System: Linux lunar-crush-vps 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Version of software: Latest files (as 2022-04-26)

**Workaround**
_The error is on line 92 in /helpers/misc.py which is debug log._
Remove the `vt:{crush['vt']:8f}` part from this line, and the script should be running fine.

**Comment by cyberjunky** [comment]
Thank you for reporting, it seems LunarCrush removed a field from the data.
I have updated the code
