### ISSUE TITLE
Error fetching 3Commas price

### ISSUE THREAD

**Issue by Gh61** [cyberjunky/3commas-cyber-bots#160]
**Describe the bug**
When using altrank.py script, fetching BTC price from 3commas fails on:
```
2022-11-03 10:44:36 - altrank - INFO - 3C Cyber Bot-Helper altrank
2022-11-03 10:44:36 - altrank - INFO - Started on Thursday 10:44:36 2022-11-03
2022-11-03 10:44:36 - altrank - INFO - Notifications are enabled
2022-11-03 10:44:36 - altrank - INFO - Loaded configuration from '/root/3commas-cyber-bots/altrank.ini'
2022-11-03 10:44:36 - altrank - INFO - Reloaded configuration from '/root/3commas-cyber-bots/altrank.ini'
2022-11-03 10:44:36 - altrank - INFO - Fetched 3Commas pairs blacklist OK (7 pairs)
2022-11-03 10:44:36 - altrank - INFO - Fetched 3Commas price OK (20311.34)
Traceback (most recent call last):
  File ".../3commas-cyber-bots/./altrank.py", line 360, in <module>
    usdtbtcprice = get_threecommas_btcusd(logger, api)
  File ".../3commas-cyber-bots/helpers/threecommas.py", line 74, in get_threecommas_btcusd
    if isnan(price):
TypeError: must be real number, not str
```

**To Reproduce**
- `git pull` to get latest version
- instal missing requirements if any
- run `altrank.py`

**Expected behavior**
Should run flawlessly

**Environment:**
 - Python version: 3.9.7
 - Operating System: Ubuntu
 - Version of software: latest

**How to fix**
I simply fixed the script by adding typecheck and converting string to float (I am not a python developer TBH):
File: `helpers/threecommas.py`
Edit:
```python
...
if data:
    price = data["last"]
    logger.info(f"Fetched 3Commas price OK ({price})")
    if isinstance(price, str): # <-- NEW CODE
        price = float(price)   # <-- NEW CODE
else:
...
```

**Comment by Gh61** [comment]
OT:
BTW I am trying to find out, what happened to LunarCrush v2 API, it's not working for 3 days straight (getting HTTP 500).
I only hope, that they did not kill this API.
Can't find any info about it.

**Comment by dangalv** [comment]
I have the same error, I bought the api for one day from lunarcrush and the error persists

**Comment by bonjo75** [comment]
Same error here, from 1st November. It seems not related to API key but more to have changed the fenching?

**Comment by dangalv** [comment]
> Same error here, from 1st November. It seems not related to API key but more to have changed the fenching?

I really don't know, it may be that the new api needs another way to encode the script so that it can fetching the coins

**Comment by Gh61** [comment]
> I really don't know, it may be that the new api needs another way to encode the script so that it can fetching the coins

Yes, this script is using the v2 API and I think that it will soon not be supported anymore. But I am expecting some announcement about this and maybe the api will be returning 404 after that and not 500. Thou it's true, that the site for this api (legacy.lunarcrush.com) is no longer available. 
Then we will have to rewrite the script to support the new (paid) API v3.

Currently there are some issues when navigating through the lunarcrush site, so I hope that this is only some error, that will be soon fixed.

**Comment by dangalv** [comment]
> Yes, this script is using the v2 API and I think that it will soon not be supported anymore. But I am expecting some announcement about this and maybe the api will be returning 404 after that and not 500. Thou it's true, that the site for this api (legacy.lunarcrush.com) is no longer available. Then we will have to rewrite the script to support the new (paid?) API v3.
> 
> Currently there are some issues when navigating through the lunarcrush site, so I hope that this is only some error, that will be soon fixed.

Yes, I was seeing that in the scripts in the "helper" folder, and indeed it uses the v2 api and actually the api is v3. I was reading some of the api documentation from lunarcrush, and I think that some requests to the api have changed, we should change some of that to the scripts in the helper folder such as datasources, which I think is where the connection to the LC api is. I'm going to keep trying although I'm sure I won't get anything, but I won't lose anything.

**Comment by bonjo75** [comment]
I modified the part of the file misc.py changing the request for fetching, the helper is not giving error but cannot fetch any coins from LC. I'm not so good in python, we need to wait someone else

**Comment by amargedon** [comment]
As far as I know the API is down / can no longer be used and is not freely available anymore? However, looking very short at the new documentation it seems that with an account you have 24 calls per day to fetch the /coins endpoint in which the data is located. That would require updating this script to match that endpoint indeed.

Is something I will look into, not sure when. And I will also fix the btc price as mentioned.

**Comment by cyberjunky** [comment]
@amargedon It doesn't look to me the API is free for any /coins calls (you need at least 240 credits per day 24 * 10 if you call every hour) which costs:
![image](https://user-images.githubusercontent.com/5447161/200177440-673d862b-906e-4aa1-90f5-947b51edf715.png)

**Comment by amargedon** [comment]
Ah yes you are right. I missed in the overview the credits part and saw only the number of calls you are allowed to do per day.

**Comment by thematikma** [comment]
I added funds to Lunarcrush and had a test with the new code. The good news is, there wasn't any error and the calls went through. But I do not have level 4 status on LC, which I suppose is now needed for altrank and galaxyscore :(

>- INFO - Fetched 3Commas market data for 'binance' OK (1444 pairs)
2022-11-06 17:08:50 - galaxyscore10 - INFO - Bot exchange: Binance (binance)
2022-11-06 17:08:50 - galaxyscore10 - INFO - None of the 3c-tools bot-assist suggested pairs have been found on the Binance (binance) exchange!
2022-11-06 17:08:51 - galaxyscore10 - INFO - Bot base currency: USDT
2022-11-06 17:08:51 - galaxyscore10 - INFO - Fetched 3Commas account market code in real mode OK (binance)
2022-11-06 17:08:51 - galaxyscore10 - INFO - Fetched 3Commas market data for 'binance' OK (1444 pairs)
2022-11-06 17:08:51 - galaxyscore10 - INFO - Bot exchange: Binance (binance)
2022-11-06 17:08:51 - galaxyscore10 - INFO - None of the 3c-tools bot-assist suggested pairs have been found on the Binance (binance) exchange!
2022-11-06 17:08:51 - galaxyscore10 - INFO - Next update in 1:00:00 at 18:08:51
2022-11-06 17:08:51 - galaxyscore10 - INFO - Notifying 1 service(s) asynchronously.
2022-11-06 17:08:51 - galaxyscore10 - INFO - Sent Discord notification.
2022-11-06 17:19:14 - galaxyscore10 - INFO - 3C Cyber Bot-Helper galaxyscore10
2022-11-06 17:19:14 - galaxyscore10 - INFO - Started on Sunday 17:19:14 2022-11-06
2022-11-06 17:19:14 - galaxyscore10 - INFO - Notifications are enabled
2022-11-06 17:19:14 - galaxyscore10 - INFO - Loaded configuration from '/home/thomas/3commas-cyber-bots-ini//galaxyscore10.ini'
2022-11-06 17:19:14 - galaxyscore10 - INFO - Reloaded configuration from '/home/thomas/3commas-cyber-bots-ini//galaxyscore10.ini'
2022-11-06 17:19:14 - galaxyscore10 - INFO - Fetched 3Commas pairs blacklist OK (143 pairs)
2022-11-06 17:19:14 - galaxyscore10 - INFO - Fetched 3Commas price OK (21215.5)
2022-11-06 17:19:15 - galaxyscore10 - INFO - Fetched LunarCrush ranking OK (150 coins)
2022-11-06 17:19:15 - galaxyscore10 - INFO - Bot base currency: USDT
2022-11-06 17:19:15 - galaxyscore10 - INFO - Fetched 3Commas account market code in real mode OK (binance)
2022-11-06 17:19:16 - galaxyscore10 - INFO - Fetched 3Commas market data for 'binance' OK (1444 pairs)
2022-11-06 17:19:16 - galaxyscore10 - INFO - Bot exchange: Binance (binance)
2022-11-06 17:19:16 - galaxyscore10 - INFO - None of the 3c-tools bot-assist suggested pairs have been found on the Binance (binance) exchange!
2022-11-06 17:19:16 - galaxyscore10 - INFO - Bot base currency: USDT
2022-11-06 17:19:16 - galaxyscore10 - INFO - Fetched 3Commas account market code in real mode OK (binance)
2022-11-06 17:19:16 - galaxyscore10 - INFO - Fetched 3Commas market data for 'binance' OK (1444 pairs)
2022-11-06 17:19:16 - galaxyscore10 - INFO - Bot exchange: Binance (binance)
2022-11-06 17:19:16 - galaxyscore10 - INFO - None of the 3c-tools bot-assist suggested pairs have been found on the Binance (binance) exchange!
2022-11-06 17:19:16 - galaxyscore10 - INFO - Next update in 1:00:00 at 18:19:16
2022-11-06 17:19:16 - galaxyscore10 - INFO - Notifying 1 service(s) asynchronously.
2022-11-06 17:19:17 - galaxyscore10 - INFO - Sent Discord notification.

![image](https://user-images.githubusercontent.com/37190356/200182217-a35991b5-0cba-4198-960d-c9209d573669.png)

**Comment by cyberjunky** [comment]
@thematikma where is that stated on the LC websites, that makes it even a worse business case than it was with the credits alone.
Can you enable debug in galaxy10.ini and post result of the lunarcrush calls? If you also have downloaded the latest helpers/logging.py the debug output is shown in console as wel...

**Comment by cyberjunky** [comment]
It seems to have downloaded data, maybe something else needs a fix
```Fetched LunarCrush ranking OK (150 coins)```

**Comment by thematikma** [comment]
Only these vague hints. Something written in docs or FAQ about that, I could not find.
![image](https://user-images.githubusercontent.com/37190356/200183146-33f3a8a7-bcda-4f0f-907b-d8a5dc797023.png)

![image](https://user-images.githubusercontent.com/37190356/200183036-a113f806-9f4c-4eaa-9f2c-ffc2ea89f9ca.png)

![image](https://user-images.githubusercontent.com/37190356/200183076-3291eb54-bc91-4bb3-bcd4-c47bd515e2f1.png)

**Comment by cyberjunky** [comment]
Please enable debug and rerun to get the debug output to share, because it even looks the calls you made are free to be honest.

The screenshots looks like to be for webgui access, the API calls pricing is different, would be strange if every page refresh would cost money.

**Comment by thematikma** [comment]
> Please enable debug and rerun to get the debug output to share, because it even looks the calls you made are free to be honest.
> 
> The screenshots looks like to be for webgui access, the API calls pricing is different, would be strange if every page refresh would cost money.

yeah you are right. Debug is on now, and it seems altrank and vol limits are too high. I will post results.

**Comment by thematikma** [comment]
[debug output.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/9946326/debug.output.txt)

**Comment by thematikma** [comment]
I will try to lower limits and get back with another output

**Comment by cyberjunky** [comment]
Yes looks like all is normal, but almost no volume lats months.
Can you check if the credits used are deducted from your total somewhere?

Thanks for testing this BTW!

**Comment by thematikma** [comment]
> Yes looks like all is normal, but almost no volume lats months. Can you check if the credits used are deducted from your total somewhere?
> 
> Thanks for testing this BTW!

Didn't realize low volume until then! I have lowered parameters drastically (maxalt 5000 and mingalaxy 0) just for testing and did get a pair change! 
And sill no credits deduced after 6 calls. I will let it run on disabled bots hourly and have a look later on again.

>2022-11-06 17:59:08 - galaxyscore10 - INFO - Bot 'galaxyscore10 Safira with SL - ' with id '7231838' updated with pair 'USDT_DAR'

**Comment by cyberjunky** [comment]
Thanks man! Where exactly did you have add credits? The new LC website is not my favorite one to be honest:
![image](https://user-images.githubusercontent.com/5447161/200184847-d7ab349f-877e-4fca-9ff3-2c2b60704294.png)

**Comment by thematikma** [comment]
Yeah not that user friendly. It should be on Hamburger menu -> Developers -> API Pricing
And no problem, we can all put a good use to if, it runs again. I can read a bit code and understand API basics, but no practical things yet (should stop inhibit myself to not to 😅)
Thank you and all active contributors for all the work so far!

**Comment by bonjo75** [comment]
Guys, I'm available to test on Altrank if someone share the new files with me. I'm Level 4 on LC

**Comment by cyberjunky** [comment]
> Guys, I'm available to test on Altrank if someone share the new files with me. I'm Level 4 on LC

They are here on the github. eg https://github.com/cyberjunky/3commas-cyber-bots/blob/main/altrank.py

It uses the same code as @thematikma is testing galaxyscore with, so I guess it will work. but i'm kinda curious if/when credits are deducted from your total.

**Comment by cyberjunky** [comment]
$9 for 20000 credits will give 83 days of 24 calls per day... but "or ~10day of api acess" seems to suggest there is a minimum usage of $1 per day? I'm so confused, my head is not clear enough to read the small letters...
![image](https://user-images.githubusercontent.com/5447161/200186380-5fbb8f12-36a1-4640-bb3e-f71b1339f349.png)

**Comment by thematikma** [comment]
> but i'm kinda curious if/when credits are deducted from your total.

I would reckon one has to spend at least $0.01 worth of credits to really show up  

@bonjo75 
>Guys, I'm available to test on Altrank if someone share the new files with me. I'm Level 4 on LC

I think I was wrong with the assumption, that Level 4 is necessary (seems to be the case for visuals on the webpage, but not for the api.)
I was getting pais, but volume limits inhibited changes to the bot.

**Comment by cyberjunky** [comment]
Curious what it does during a few days...

**Comment by bonjo75** [comment]
`2022-11-06 19:34:47 - altrank - DEBUG - https://lunarcrush.com:443 "GET /api3/coins?sort=alt_rank&limit=4000 HTTP/1.1" 500 106
2022-11-06 19:34:47 - altrank - ERROR - Fetching LunarCrush data failed with code 500: {"error":"Error: You must have at least $1 USD in your LunarCrush payments account to use this endpoint."}`


this is the reply, Seems that even on Lv 4 need to recharge the account

**Comment by bonjo75** [comment]
![image](https://user-images.githubusercontent.com/102473709/200192197-24d45a46-279c-4121-be6f-b7a197d6c607.png)

so my result:
- new script for altarank is running
- I tried with max 4000 coins and it works but as you can see below from log, the fetching must be reversed cause for LC the rank 1 is the last coin

`2022-11-06 20:57:18 - altrank - DEBUG - rank:  1  acr:3972   gs:30.0   s:CLL      'Attention Mining         '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  2  acr:3971   gs:30.0   s:OMEN     'OmenCoin                 '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  3  acr:3970   gs:0.0   s:AI       'POLY AI                  '   volume in btc:        0.00   categories:['erc20']
2022-11-06 20:57:18 - altrank - DEBUG - rank:  4  acr:3969   gs:0.0   s:ACP      'AnarchistsPrime          '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  5  acr:3968   gs:0.0   s:ICON     'Iconic                   '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  6  acr:3967   gs:30.0   s:EZW      'EZOOW                    '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  7  acr:3966   gs:0.0   s:PYX      'PyrexCoin                '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  8  acr:3965   gs:0.0   s:NMS      'Numus                    '   volume in btc:        0.00   categories:[]
2022-11-06 20:57:18 - altrank - DEBUG - rank:  9  acr:3964   gs:30.5   s:GEBT     'Green Earth Blockchain Token'   volume in btc:        0.00   categories:['algorand']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 10  acr:3963   gs:0.0   s:AKAMOON  'Akamoon Inu              '   volume in btc:        0.00   categories:['bsc', 'defi', 'nft']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 11  acr:3962   gs:30.5   s:MXDT     'The Metaverse Exchange DAO'   volume in btc:        0.00   categories:['erc20', 'polygon', 'defi']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 12  acr:3961   gs:0.0   s:BMB      'Bamboo Swap              '   volume in btc:        0.00   categories:['defi', 'nft']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 13  acr:3960   gs:0.0   s:SHEEB    'Sheeb Inu                '   volume in btc:        0.00   categories:['bsc', 'meme']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 14  acr:3959   gs:0.0   s:MINIXRP  'MiniRipple               '   volume in btc:        0.00   categories:['bsc', 'defi']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 15  acr:3958   gs:0.0   s:BABYTSUKA 'Dwagon                   '   volume in btc:        0.00   categories:['erc20', 'defi', 'nft', 'meme']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 16  acr:3957   gs:0.0   s:KOYO     'Yofune Nushi             '   volume in btc:        0.00   categories:['erc20', 'defi', 'nft', 'meme']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 17  acr:3956   gs:30.0   s:ZIX      'Coinzix                  '   volume in btc:        0.00   categories:['bsc']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 18  acr:3955   gs:30.0   s:CLUB     'Club0x                   '   volume in btc:        0.00   categories:['bsc', 'defi', 'stablecoin']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 19  acr:3954   gs:0.0   s:LGG      'Liberty Gaming           '   volume in btc:        0.00   categories:['bsc']
2022-11-06 20:57:18 - altrank - DEBUG - rank: 20  acr:3953   gs:0.0   s:BEANS4   'Doge Coffee              '   volume in btc:        0.00   categories:['erc20', 'defi', 'nft', 'meme']`

- seems that on Lv 4 you need to have some credint in order to execute the fetching but is not a paid call, the limit is still not clear

**Comment by cyberjunky** [comment]
@bonjo75 strange that it's reversed, I make the correct calls, can you try latest code (helpers/datasources.py) and make sure your script has 'altrank' in it's name.
