### ISSUE TITLE
File not Found Error

### ISSUE THREAD

**Issue by pikespeak** [cyberjunky/3commas-cyber-bots#30]
I have upgraded the Repo from 57ffeff..6c6d672

2021-11-28 00:55:21 - altrank.py - 3Commas bot helper altrank
2021-11-28 00:55:21 - altrank.py - Started at Sunday 00:55:21 28-11-2021
2021-11-28 00:55:21 - altrank.py - Loaded configuration from '/var/git/3commas-cyber-bots/altrank.ini'
2021-11-28 00:55:21 - altrank.py - Notifications are disabled
2021-11-28 00:55:21 - altrank.py - Reloaded configuration from '/var/git/3commas-cyber-bots/altrank.ini'
2021-11-28 00:55:21 - altrank.py - Fetched 3Commas pairs blacklist OK (12 pairs)
2021-11-28 00:55:21 - altrank.py - Fetched 3Commas BTC price OK (54475.15 USDT)
2021-11-28 00:55:22 - altrank.py - Fetched LunarCrush ranking OK (100 coins)
2021-11-28 00:55:23 - altrank.py - Bot base currency: BUSD
2021-11-28 00:55:23 - altrank.py - Bot minimal 24h BTC volume: 500.0
Traceback (most recent call last):
  File "altrank.py", line 648, in <module>
    find_pairs(botdata)
  File "altrank.py", line 430, in find_pairs
    marketcode = get_threecommas_account(thebot["account_id"])
  File "altrank.py", line 302, in get_threecommas_account
    for account in data:
TypeError: 'NoneType' object is not iterable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_var_git_3commas-cyber-bots_altrank.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "altrank.py", line 648, in <module>
    find_pairs(botdata)
  File "altrank.py", line 430, in find_pairs
    marketcode = get_threecommas_account(thebot["account_id"])
  File "altrank.py", line 302, in get_threecommas_account
    for account in data:
TypeError: 'NoneType' object is not iterable

**Comment by cyberjunky** [comment]
@pikespeak Hi thanks for reporting, please see FAQ #8, you need to add AccountRead permission to the 3Commas API keys
I will change the code so this is more obvious.

**Comment by cyberjunky** [comment]
Closing issue, if you still have this issue let me know.
