### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Trigie** [cyberjunky/3commas-cyber-bots#7]
Galaxyscore was running for some days without any problems and it suddenly quited. When I try to restart the same error pops up.

['BTC_CELR', 'BTC_MANA', 'BTC_FIDA', 'BTC_MOVR', 'BTC_SYS', 'BTC_KSM', 'BTC_DGB']
2021-11-11 22:45:02,722 - galaxyscore - INFO - Next update in 900 Seconds at 23:00:02
2021-11-11 23:00:02,729 - galaxyscore - INFO - Loaded configuration from 'galaxyscore.ini'
2021-11-11 23:00:03,337 - galaxyscore - INFO - Fetched 3Commas pairs blacklist OK (179 pairs)
2021-11-11 23:00:03,408 - galaxyscore - INFO - Fetched 3Commas BTC price in USDT 65164.28 OK
2021-11-11 23:00:04,271 - galaxyscore - INFO - Fetched LunarCrush Top X gs OK (50 coins)
2021-11-11 23:00:04,271 - galaxyscore - INFO - Finding the best pairs for Binance Main exchange
2021-11-11 23:00:04,326 - galaxyscore - INFO - Fetched 3Commas market data for binance OK (1312 pairs)
Traceback (most recent call last):
  File "/bot/3commas-cyber-bots/galaxyscore.py", line 659, in <module>
    find_pairs(botdata)
  File "/bot/3commas-cyber-bots/galaxyscore.py", line 427, in find_pairs
    if float(lunacrush[coin]) < float(minvolume):
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by cyberjunky** [comment]
@Trigie thank you for reporting, so either the lunarcrush data was empty or the bots minimal 24hr volume. I will build in more checks..

**Comment by cyberjunky** [comment]
@Trigie I created version 0.6.7 with extra check, and working 24 hr minimal check, found another but, thanks for reporting!

**Comment by cyberjunky** [comment]
@Trigie I will close this issue, if you still have this issue (or another one) please open an new issue for it.
