### ISSUE TITLE
 TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by zegmaarmanu** [cyberjunky/3commas-cyber-bots#96]
Hi,

first of all, thanks a lto for your work, it resulted in a couple of really nice bot setups.

The bot was running fine for a few days, but then I ran into the following error:

2022-02-23 09:39:12 - galaxyscore - INFO - 3C Cyber Bot-Helper galaxyscore
2022-02-23 09:39:12 - galaxyscore - INFO - Started on Wednesday 09:39:12 2022-02-23
2022-02-23 09:39:12 - galaxyscore - INFO - Notifications are disabled
2022-02-23 09:39:12 - galaxyscore - INFO - Loaded configuration from '/home/ZegMaarManu/3commas-cyber-bots/galaxyscore.ini'
2022-02-23 09:39:12 - galaxyscore - INFO - Reloaded configuration from '/home/ZegMaarManu/3commas-cyber-bots/galaxyscore.ini'
2022-02-23 09:39:12 - galaxyscore - INFO - Fetched 3Commas pairs blacklist OK (24 pairs)
2022-02-23 09:39:12 - galaxyscore - INFO - Fetched 3Commas BTC price OK (38682.82 USDT)
2022-02-23 09:39:12 - galaxyscore - INFO - Fetched LunarCrush ranking OK (150 coins)
Traceback (most recent call last):
  File "/home/ZegMaarManu/3commas-cyber-bots/./galaxyscore.py", line 278, in <module>
    lunarcrush_pairs(data)
  File "/home/ZegMaarManu/3commas-cyber-bots/./galaxyscore.py", line 81, in lunarcrush_pairs
    minvolume = float(thebot["min_volume_btc_24h"])
**TypeError: float() argument must be a string or a number, not 'NoneType'**

I saw that a similar issue was reported a few months ago...

Hope you can help...

Best regards,
Manu

**Comment by zegmaarmanu** [comment]
FYI, a similar error pops up on the Altrank bot helper.
Cheers
